### ISSUE TITLE
After pulling update no libForwardLookingGazeboSonar.so file found

### ISSUE THREAD

**Issue by elishafer** [Brazilian-Institute-of-Robotics/forward_looking_sonar_gazebo#14]
```
[Err] [Plugin.hh:165] Failed to load plugin libForwardLookingGazeboSonar.so: libForwardLookingGazeboSonar.so: cannot open shared object file: No such file or directory
```
in `/catkin_ws/install/lib/` only `libForwardLookingSonarGazebo.so` and `libFowardLookingGazeboSonar.so` found.

**Comment by elishafer** [comment]
Fixed this by changing line 7 in [gazebo_car_sonar.xacro](/xacro/[gazebo_car_sonar.xacro) to `<plugin name="SonarVisual" filename="libForwardLookingSonarGazebo.so" >`

**Comment by ivan1993br** [comment]
Yes, my mistake, the `libForwardLookingSonarGazebo.so` is the correct.
