### ISSUE TITLE
Horizontal field of view value has no effect.

### ISSUE THREAD

**Issue by elishafer** [Brazilian-Institute-of-Robotics/forward_looking_sonar_gazebo#9]
In [gazeb_car_sonar.xacro](https://github.com/Brazilian-Institute-of-Robotics/forward_looking_sonar_gazebo/blob/master/xacro/gazebo_car_sonar.xacro)
When changing hfov has no effect. On the other hand changing vfov affects both horizontal fov and vertical.

**Comment by ivan1993br** [comment]
It is true, this problem was already mapped, I fixed it on this new pull request

**Comment by elishafer** [comment]
Cool, thanks =]
I have a few questions about the repo in general, I don't really know where to ask so I'll do it here:
I read the [research paper mentioned in the documentation](https://www.sciencedirect.com/science/article/pii/S0097849317301371) and I was very impressed.
I'm starting research on an AUV and wanted to get a simulator up and running.

Is the plan to have this repo have the same capabilities as the one in the research paper?
